name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Tests
      run: |
        python -m unittest discover tests

  # Блок деплоя (упрощенный, через Deploy Hook Render)
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Render
        # Вам нужно будет вставить свой RENDER_DEPLOY_HOOK_URL в Secrets репозитория GitHub
        run: curl ${https://api.render.com/deploy/srv-d4qqrrje5dus73ethc60?key=eTAcLvm5RPw}